version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: FarDragi.Hanabi/Dockerfile
      args:
        GITHUB_NAME: ${GITHUB_NAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_OWNERGUILD: ${BOT_OWNERGUILD}
      CHANNELS_STARBOARD: ${CHANNELS_STARBOARD}
      CHANNELS_CANDYDROP: ${CHANNELS_CANDYDROP}
      DATABASE_URL: Server=database;Database=hanabi;User Id=root;Password=${DATABASE_PASSWORD};
  database:
    image: mariadb:10.11.5
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes: 
  mariadb: